package data.entities.autoentity;

import javax.persistence.Column;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Field;

/**
 * Created by Mona on 5/8/2015.
 */
public class makeEntityFile{

    public void make(Object object, String nameFile) throws IOException {


        Class clazz = object.getClass();

        Field[] field = clazz.getFields();

        //System.out.println(field[0].getName() + " monaaaaaaaaa ");

        String content = "import org.hibernate.annotations.GenericGenerator;\n" +
                "import org.hibernate.annotations.Type;\n" +
                "\n" +
                "import javax.persistence.*;\n" +
                "import java.sql.Timestamp;\n" +
                "import java.util.UUID;\n" +
                "\n" +
                "/**\n" +
                " * Created by root on 2/22/15.\n" +
                " */\n" +
                "@Table(name = \"Action\")\n" +
                "@Entity\n" +
                "public class Entity {\n";

        File file = new File("src\\main\\java\\data\\entities\\entityfile\\"+ nameFile +".java");

        FileWriter fw = new FileWriter(file.getAbsoluteFile());
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write(content);

        //   Column annotation = annotationsMap.get(fieldName);

        for (Field fieldName : field) {

            if (fieldName.isAnnotationPresent(Column.class)) {
                String type = fieldName.getType().getSimpleName();
                String name = fieldName.getName();

                content = "public " + type + " " + name + ";\n";
                bw.write(content);

                System.out.println(
                        "@Column(autoGenerated=true) is set for field [" + name
                                + "] of class [" + type
                                + "] ");

                content = "    @Column(name = " + name + ")\n" + "    @Basic\n" +
                        "    public String get" + name + "(){\n" +
                        "        return" + name + ";\n" +
                        "    }\n" +
                        "    public void set" + name + "(" + type + " " + name + ") {\n" +
                        "        this." + name + " = " + name + ";\n" +
                        "    }\n \n \n ";


                bw.write(content);


            }
            content = "}";
            bw.write(content);
            bw.close();
            // }
        }
    }

    }


